export const tasks = [
  {
    id: 1,
    category: 'Shopping',
    title: 'Shopping',
    status: 'pending',
    description: "Getessentials from Trader Joe's",
  },
  {
    id: 2,
    category: 'Shopping',
    title: 'Shoes',
    status: 'pending',
    description: 'Purchaserunning shoes',
  },
  {
    id: 3,
    category: 'Work',
    title: 'Presentation',
    status: 'pending',
    description: 'Createslides for team meeting',
  },
  {
    id: 4,
    category: 'Work',
    title: 'Review',
    status: 'pending',
    description: "Reviewfrontend team's pull request",
  },
  {
    id: 5,
    category: 'Home',
    title: 'Garage',
    status: 'pending',
    description: 'Organizetools and discard unnecessary items',
  },
  {
    id: 6,
    category: 'Home',
    title: 'Plants',
    status: 'pending',
    description: 'Water indoorand outdoor plants',
  },
  {
    id: 7,
    category: 'Health',
    title: 'Exercise',
    status: 'pending',
    description: 'Complete30-minute yoga session',
  },
  {
    id: 8,
    category: 'Health',
    title: 'Appointment',
    status: 'pending',
    description: 'Visitdentist for routine check-up',
  },
];
